WIP: Refactor
alimoghaddam2000/Forth pull request #1
Opened 2023-07-11 11:42 UTC by alimoghaddam2000

2023-07-23 07:42 UTC, ahmad-siavashi requested changes

2023-07-23 07:42 UTC, ahmad-siavashi commented on src/graphics.c
> +        "Snake!!",
It looks like the implementation is still aimed for Snake!

2023-07-27 08:06 UTC, ahmad-siavashi commented on Makefile
> +
Usually `Final.out` is not something one would expect as the entry point of a program. If you changed it consider an update to the README.md file as well.

2023-07-27 08:09 UTC, ahmad-siavashi commented
Excellent. You're ready to go and merge this PR. Update the document, i.e. README.md, if required.
Open more PRs for other changes in future.

2023-07-27 09:39 UTC, merged

2023-07-27 09:53 UTC, alimoghaddam2000 commented
Hi,
I hope this email finds you well. I wanted to express my gratitude for taking the time to review my code for the project. Your feedback and suggestions were incredibly valuable and have helped me improve my understanding of the concepts we have been learning.

I did update README.md and merge develop branch into main branch and I wanted to discuss the next steps for the project with you. I have a couple of ideas in mind and would appreciate your guidance on which direction to take.

Firstly, I was considering creating a wiki for my repository on GitHub. This would serve as a documentation resource for the project, providing explanations of the code structure, functionality, and usage instructions. It would be a valuable addition for future contributors or users of the project. I would like to know your thoughts on this and whether you believe it would be beneficial to proceed with creating the wiki.

Additionally, I have been working on implementing "auto completion" functionality in the project. This feature would enhance the user experience by suggesting possible commands or options as the user types. I am confident that this addition would greatly improve the usability of the project. Therefore, I would like to request a deadline for completing this task, so that I can allocate the necessary time and resources to finish it.

I would greatly appreciate your guidance and input on these next steps. Your expertise and advice have been instrumental in my progress, and I am eager to continue learning and improving.

Thank you once again for your time and support. I look forward to hearing from you soon.

Best regards,
Ali
________________________________
From: Ahmad Siavashi ***@***.***>
Sent: Thursday, July 27, 2023 8:09 AM
To: alimoghaddam2000/Forth ***@***.***>
Cc: alimoghaddam2000 ***@***.***>; Author ***@***.***>
Subject: Re: [alimoghaddam2000/Forth] WIP: Refactor (PR #1)


Excellent. You're ready to go and merge this PR. Update the document, i.e. README.md, if required.
Open more PRs for other changes in future.

—
Reply to this email directly, view it on GitHub<https://github.com/alimoghaddam2000/Forth/pull/1#issuecomment-1653111882>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AUNSV6JYI7REY5PPQ7HNWRDXSIO4TANCNFSM6AAAAAA2F4AVYM>.
You are receiving this because you authored the thread.Message ID: ***@***.***>